// Import stylesheets
import './style.css';

// Write Javascript code!
const appDiv = document.getElementById('app');
appDiv.innerHTML = `<h1>hello put this command in the command block



                                           /give @p written_book{pages:['{"text":"Minecraft Tools book"}','["",{"text":"summon lama","color":"green","clickEvent":{"action":"run_command","value":"/function milk:cool"}},{"text":"\\n","color":"reset"},{"text":"summon OP loot","color":"aqua","clickEvent":{"action":"run_command","value":"/function milk:op"}},{"text":"\\n ","color":"reset"},{"text":"get a firework","color":"yellow","clickEvent":{"action":"run_command","value":"/give @p firework_rocket{Fireworks:{Flight:2,Explosions:[{Type:2,Flicker:0,Trail:1,Colors:[I;3887386,2437522,8073150,14188952,4312372,14602026,15435844],FadeColors:[I;11743532,3887386,2437522,8073150,14188952,4312372,14602026,15790320]}]}} 1"}},{"text":"\\n","color":"reset"},{"text":"summon a challenging boss to fight","color":"blue","clickEvent":{"action":"run_command","value":"/summon ravager ~ ~1 ~ {Passengers:[{id:skeleton,HandItems:[{Count:1,id:bow,tag:{Enchantments:[{id:unbreaking,lvl:3},{id:power,lvl:5},{id:punch,lvl:2},{id:mending,lvl:1}]}},{Count:1,id:diamond_pickaxe,tag:{Enchantments:[{id:efficiency,lvl:5},{id:unbreaking,lvl:3},{id:fortune,lvl:3},{id:mending,lvl:1}]}}],ArmorItems:[{Count:1,id:netherite_boots,tag:{Enchantments:[{id:soul_speed,lvl:3},{id:protection,lvl:4},{id:feather_falling,lvl:4},{id:thorns,lvl:3},{id:depth_strider,lvl:3},{id:unbreaking,lvl:3},{id:mending,lvl:1}]}},{Count:1,id:netherite_leggings,tag:{Enchantments:[{id:protection,lvl:4},{id:thorns,lvl:3},{id:unbreaking,lvl:3},{id:mending,lvl:1}]}},{Count:1,id:netherite_chestplate,tag:{Enchantments:[{id:protection,lvl:4},{id:thorns,lvl:3},{id:unbreaking,lvl:3},{id:mending,lvl:1}]}},{Count:1,id:netherite_helmet,tag:{Enchantments:[{id:protection,lvl:4},{id:respiration,lvl:3},{id:aqua_affinity,lvl:1},{id:thorns,lvl:3},{id:unbreaking,lvl:3},{id:mending,lvl:1}]}}],CustomName:\\"\\\\\\"boss\\\\\\"\\",HandDropChances:[1.0f,0.0f],ArmorDropChances:[1.0f,1.0f,1.0f,1.0f],ActiveEffects:[{Id:5,Amplifier:0,Duration:999999},{Id:10,Amplifier:0,Duration:999999},{Id:11,Amplifier:0,Duration:999999}]}]}"}},{"text":"\\n\\n\\n\\n\\n\\n","color":"reset"},{"text":"to make a custom vilager use this link\\nclick here","clickEvent":{"action":"open_url","value":"https://www.digminecraft.com/generators/villager_trade.php"}}]'],title:"data pack book",author:"http://minecraft.tools/"}</h1>`;